name: Performance Test

on:
  push:
    branches:
      - 'master'
      - 'next'
    paths:
      - 'packages/x-charts*/**'
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - 'master'
      - 'next'

jobs:
  performance-test:
    name: Benchmark Charts
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      # Ensure we are running on the prod version of our libs
      - run: pnpm --filter "@mui/x-charts-premium..." build

      - uses: actions/download-artifact@v4
        with:
          name: charts-benchmarks-results-master.json
          path: ./results-master
      - run: mv ./results-master/baseline-results.json ./test/performance-charts/baseline-results.json

      - name: Run performance tests
        run: pnpm --filter @mui-x-internal/performance-charts test:performance:ci

      - name: Compare performance results
        uses: actions/github-script@v7
        env:
          BASELINE_PATH: ./test/performance-charts/baseline-results.json
          COMPARE_PATH: ./test/performance-charts/results.json
          THRESHOLD: 0.1
        with:
          script: |
            const { default: ciBenchmark } = await import('${{ github.workspace }}/test/performance-charts/scripts/ci-benchmark.js');
            await ciBenchmark({github, context, core});
